#' @title Bioclim variables from \emph{TraCESahul} climate data
#'
#' @description
#' Calculates bioclimatic variables
#' (\href{https://www.worldclim.org/data/bioclim.html}{BIO1–BIO19}) from monthly
#' \emph{TraCESahul}climate data using
#' \code{\link[fastbioclim:derive_bioclim]{fastbioclim::derive_bioclim}}.
#' The function requires monthly maximum temperature, minimum temperature, and
#' precipitation rasters, performs optional precipitation scaling, processes each
#' year independently, and returns either a list of annual bioclim stacks or
#' collated multi-year rasters for each requested bioclimatic variable.
#'
#' @param tasmax A \code{\link[terra:tapp]{SpatRaster}} ideally imported with
#'   \code{\link{import_TraCESahul}} that represents monthly maximum
#'   temperature.
#' @param tasmin A \code{SpatRaster} ideally imported with
#'   \code{\link{import_TraCESahul}} that represents monthly minimum
#'   temperature.
#' @param pr A \code{SpatRaster} ideally imported with
#' \code{\link{import_TraCESahul}} that represents monthly precipitation.
#' @param bioclims Integer vector of bioclimatic variable indices to compute.
#'   Only indices 1–19 are valid.
#' @param pr_scale Numeric; scaling factor applied to precipitation values if
#'   their units are \code{"kg m-2 s-1"}. Ignored if precipitation units are not
#'   in flux form.
#' @param new_units What the units of the input precipitation will be following
#' scaling with \code{pr_scale}. Not checked.
#' @param collate Logical; if \code{TRUE} (default), the output is collated into
#'   one raster per bioclimatic variable across all years. If \code{FALSE},
#'   returns a list containing a \code{\link[terra:sds]{sds}} object for each year.
#' @param outdir Directory where yearly outputs and the final RDS file should be
#'   written. If \code{NULL}, a temporary directory is created.
#' @param ... Additional arguments passed to
#'   \code{\link[fastbioclim:derive_bioclim]{fastbioclim::derive_bioclim()}}.
#'
#' @details
#' If precipitation is supplied in \code{"kg m-2 s-1"}, it is multiplied by
#' \code{pr_scale} prior to bioclimatic calculations. The default scaling converts
#' from \code{"kg m-2 s-1"} to \code{"mm/day"}. To convert to
#' monthly totals in \code{mm/month}, a vector of month-specific multipliers
#' can be supplied:
#'
#' \code{pr_scale = 86400 * c(31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)}.
#'
#' The function processes each year separately, producing year-specific
#' subdirectories containing bioclim raster files generated by
#' \code{\link[fastbioclim:derive_bioclim]{derive_bioclim}}.
#'
#' @return
#' If \code{collate = TRUE}, returns a named list where each element is a
#' multilayer \code{SpatRaster} containing all years for a single bioclimatic
#' variable (e.g., \code{bio01_1850}, \code{bio01_1851}, …). Output years are
#' taken from the input rasters.
#'
#' If \code{collate = FALSE}, returns a named list of yearly
#' \code{terra::sds} objects, each containing the bioclimatic layers produced
#' for that year.
#'
#' In all cases, an RDS file named \code{bioclims_TraCESahul.RDS} is written to
#' \code{outdir}, containing the per-year results.
#'
#' @examples
#' \dontrun{
#' # Calculate bioclims 1:19 on the summarised data
#' bioclims <- bioclim_TraCESahul(tasmax = tasmax_monthly_win,
#'                                tasmin = tasmin_monthly_win,
#'                                pr = pr_monthly_win,
#'                                bioclims = 1:19,
#'                                collate = TRUE)
#' }
#'
#' @export
#'
#' @importFrom terra rast tapp time depth names nlyr depthName depthUnit units
#' setValues varnames sds saveRDS values
#' @importFrom pbapply pblapply
#' @importFrom fastbioclim derive_bioclim
#'
bioclim_TraCESahul <- function(tasmax, tasmin, pr,
                               bioclims = 1:19,
                               pr_scale = 86400,
                               new_units = "mm/day",
                               collate = TRUE,
                               outdir = NULL,
                               ...) {
  required_args <- c("tasmax","tasmin","pr")
  supplied <- names(as.list(match.call()))[-1]
  missing <- setdiff(required_args, supplied)
  if (length(missing)) {
    stop("Missing arguments: ", paste(missing, collapse = ", "))
  }
  # restrict bioclim indices
  bad <- bioclims > 19
  if (any(bad)) {
    warning(sprintf(
      "The following bioclim indices are invalid (>19) and were removed: %s",
      paste(bioclims[bad], collapse = ", ")
    ), immediate. = TRUE, call. = FALSE)
    bioclims <- bioclims[!bad]
  }
  # create outdir if needed
  if (is.null(outdir)) {
    outdir <- file.path(tempdir(), paste0("bioclim_", format(Sys.time(), "%Y_%b_%d")))
  }
  dir.create(outdir, recursive = TRUE, showWarnings = FALSE)
  # Check input rasters
  info <- input_val(tasmax = tasmax, tasmin = tasmin, pr = pr)
  years  <- info$years
  months <- info$months
  uyears <- unique(years)
  # precipitation units
  pr_units <- terra::units(pr)[1]
  if (is.null(pr_units) || identical(pr_units, "")) {
    warning("pr was provided without units. Check that precipitation is not 'kg m-2 s-1'.",
            immediate. = TRUE)
  } else if (identical(pr_units, "kg m-2 s-1")) {
    # warn once only
    if (length(pr_scale) == 1) {
      warning(sprintf("pr was provided as 'kg m-2 s-1', multiplying by %s", pr_scale),
              immediate. = TRUE, call. = FALSE)
    } else {
      warning("pr was provided as 'kg m-2 s-1'. Applying month-specific scaling.",
              immediate. = TRUE, call. = FALSE)
    }
    pr <- terra::setValues(pr, terra::values(pr) * pr_scale)
    terra::units(pr) <- new_units
  }
  message(sprintf("A terra::sds of %s subdatasets will be saved in %s...",
                  length(uyears), normalizePath(outdir, mustWork = FALSE)))
  message(sprintf("Output files appear in subfolders: %s",
                  normalizePath(outdir, mustWork = FALSE)))
  # per-year processing
  bio_list <- terra::sds(
    pbapply::pblapply(uyears, function(yr) {
      yr_dir <- file.path(outdir, sprintf("yr_%s", yr))
      dir.create(yr_dir, showWarnings = FALSE, recursive = TRUE)
      idx <- which(years == yr)
      suppressMessages({
        bio <- fastbioclim::derive_bioclim(
          bios = bioclims,
          tmin = tasmin[[idx]],
          tmax = tasmax[[idx]],
          prcp = pr[[idx]],
          output_dir = yr_dir,
          srad = NULL,
          tavg = NULL,
          mois = NULL,
          ...
        )
      })
      terra::time(bio) <- rep(yr, terra::nlyr(bio))
      return(bio)
    })
  )
  names(bio_list) <- uyears
  # save per-year object
  terra::saveRDS(bio_list, file = file.path(outdir, "bioclims_TraCESahul.RDS"))
  # optionally collate across years. DEFAULT.
  if (!collate) {
    return(bio_list)
  }
  message("Collating bioclims...")
  bio_collate <- pbapply::pblapply(bioclims, function(b) {
    extract_bio(b, bio_list, uyears)
  })
  names(bio_collate) <- sprintf("bio%02d", bioclims)
  return(bio_collate)
}

#' Validate SpatRaster inputs for TraCESahul
#'
#' Checks that all supplied SpatRaster objects have the "TraCESahul" attribute,
#' are not annual or seasonal data, and that their years and months match.
#'
#' @param ... SpatRaster objects to validate
#' @return A list with years, months, and number of layers for each raster
#' @noRd
#'
input_val <- function(...) {
  args <- list(...)
  # keep only SpatRaster objects
  rasters <- args[vapply(args, inherits, "SpatRaster", FUN.VALUE = logical(1))]
  if (!length(rasters)) {
    stop("No SpatRaster objects supplied.", call. = TRUE)
  }
  # validate and extract metadata
  info <- lapply(names(rasters), function(nm) {
    r <- rasters[[nm]]
    if (!isTRUE(attr(r, "TraCESahul"))) {
      warning(
        sprintf("Has '%s' been imported with `import_TraCESahul` or processed with `summarise_TraCESahul`?", nm),
        immediate. = TRUE,
        call. = TRUE
      )
    }
    dname <- terra::depthName(r)
    dval  <- terra::depth(r)
    if (dname %in% c("Annual", "Season") || all(dval == 0)) {
      stop(sprintf("Supplied data in '%s' is not suitable for bioclim calculation.", nm), call. = TRUE)
    }
    return(list(years  = terra::time(r), months = dval, nlyr = terra::nlyr(r)))
  })
  names(info) <- names(rasters)
  # extract the lists for comparison
  years_list  <- lapply(info, `[[`, "years")
  months_list <- lapply(info, `[[`, "months")
  # enforce identical years and months
  if (!all(vapply(years_list, identical, FUN.VALUE = logical(1), years_list[[1]]))) {
    stop("Years do not match across all input rasters.", call. = TRUE)
  }
  if (!all(vapply(months_list, identical, FUN.VALUE = logical(1), months_list[[1]]))) {
    stop("Months (depth indices) do not match across all input rasters.", call. = TRUE)
  }
  return(list(years   = years_list[[1]], months  = months_list[[1]],
              n_layers = vapply(info, `[[`, numeric(1), "nlyr")))
}


# helper to extract one bioclim var across years
#'
#' @param b bioclim index (numeric)
#' @param bio_list list of yearly SpatRasterDataset
#' @param uyears unique years (in same order as bio_list)
#'
#' @returns SpatRaster
#' @importFrom terra rast varnames
#'
#' @noRd
extract_bio <- function(b, bio_list, uyears) {
  layers <- lapply(seq_along(bio_list), function(i) {
    x <- bio_list[[i]]
    pos <- which(names(x) == sprintf("bio%02d", b))
    x[[pos]]
  })
  out <- terra::rast(layers)
  terra::varnames(out) <- sprintf("bio%02d", b)
  names(out) <- paste0(sprintf("bio%02d", b), "_", uyears)
  out
}

